// Generated by LazyStack - modifications will be overwritten
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace PetStore
{
    public partial class Startup
    {
        public void ConfigureSvcs(IServiceCollection services)
        {
            services.AddSingleton<PetStoreRepo.Models.IPetRepo, PetStoreRepo.Models.PetRepo>();
            services.AddSingleton<PetStoreRepo.Models.IOrderRepo, PetStoreRepo.Models.OrderRepo>();
            services.AddSingleton<PetStoreRepo.Models.ITagRepo,PetStoreRepo.Models.TagRepo>();
            services.AddSingleton<PetStoreRepo.Models.ICategoryRepo,PetStoreRepo.Models.CategoryRepo>();
            services.AddScoped<PetController.IPetController, PetControllerImpl.PetControllerImpl>();
            services.AddScoped<OrderController.IOrderController, OrderControllerImpl.OrderControllerImpl>();
            services.AddDefaultAWSOptions(Configuration.GetAWSOptions());
            services.AddAWSService<Amazon.DynamoDBv2.IAmazonDynamoDB>();
        }
    }
}
