// Generated by LazyStack - modifications will be overwritten
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;

namespace LambdaFunc
{
    public partial class Startup
    {
        public void ConfigureSvcs(IServiceCollection services)
        {
        }
    }
}
